Maxon:
  config_run_sdo_verify_timeout: 50000
  print_debug_messages: true
  use_raw_commands: true
  drive_state_change_min_timeout: 2000
  drive_state_change_max_timeout: 10000 # microseconds
  min_number_of_successful_target_state_readings: 5
  display_error_codes: true
  disable_configuration_on_startup: false
  interpolation_time_period_ms: 1 # in ms. "0" disables demand value interpolation.
  # > 0 enables demand value interpolation. Target Position (and offset), Velocity
  # (and offset) are written cyclically with the interpolation time period.

Reading:
  force_append_equal_error: true
  force_append_equal_fault: false
  error_storage_capacity: 100
  fault_storage_capacity: 100

Homing:
  homing_method: -3
  homing_speeds: [540, 1] # [rpm]
  homing_acceleration: 1000 # [rpm/s]
  homing_offset: 55296 # [inc]
  home_position: 0 # [inc]
  current_threshold: 1500 # [mA]

Hardware:
  mode_of_operation:
  - CyclicSynchronousPositionMode
  - CyclicSynchronousTorqueMode
  - CyclicSynchronousVelocityMode
  - HomingMode
  position_encoder_resolution: 4096 # [counts/rev]
  gear_ratio: [1, 1] # Absolute Reduction in Datasheet, should be positive and less than 2^32 - 1
  motor_constant: 1.0 # Not being used anywhere in SDK from my observation
  working_voltage: 24 # [V]
  pole_pairs: 2 # Number of pole pairs
  speed_constant: 740 # [rpm/V]
  torque_constant: 0.0129 # [Nm/A], max value is 10,000,000
  max_current: 6 # [A] 2-3x nominal current
  nominal_current: 2.01 # [A]
  min_position: 0
  max_position: 0 # Disable checks, software position limits, can be b/w -(2^31 - 1) to (2^31 - 1)

  max_motor_speed: 15000 # [rpm]
  
  max_profile_velocity: 2000 # [rad/s]
  quick_stop_decel: 10000 # [rpm/s], max value bounded by max_acceleration (which defaults to 4'294'967'295)
  profile_decel: 10000 # [rpm/s] , max value bounded by max_acceleration (which defaults to 4'294'967'295)
  follow_error_window: 8192 # [inc] 2 revolutions

  # current_p_gain: 1.139992 # [V/A]
  # current_i_gain: 8230.973 # [V/(A*s)]
  # position_p_gain: 0.852113 # [A/rad]
  # position_i_gain: 35.693222 # [A/(rad*s)]
  # position_d_gain: 0.006712 # [(A*s)/rad]
  velocity_p_gain: 0.03 # [(A*s)/rad]
  velocity_i_gain: 1.7 # [A/rad]


  # tuned on epos studio on top motor attached to system
  current_p_gain: 1.111171 # [V/A]
  current_i_gain: 8333.075 # [V/(A*s)]
  position_p_gain: 2.918727 # [A/rad]
  position_i_gain: 122.259345 # [A/(rad*s)]
  position_d_gain: 0.020530 # [(A*s)/rad]
  # velocity_p_gain: 0.013736 # [(A*s)/rad]
  # velocity_i_gain: 0.865347 # [A/rad]

  motor_type: 10 # Changes certain value ranges. For eg: max_motor_speed
  # Allowed values for motor type: (check EPOS4 firmware ref)
  # 1 : Brushed DC (max_motor_speed limit = 100000)
  # 10: Brushless DC sine commutated (max_motor_speed limit = 50000/pole_pairs)
  # 11: Brushless DC block commutated (max_motor_speed limit = 100000/pole_pairs)